import { Bowerman } from '../js/Bowerman';
import { Daemon } from '../js/Daemon';
import { Magician } from '../js/Magician';
import '../js/baseClass';
import { Character } from '../js/baseClass';
import { Undead } from '../js/Undead';
import { Swordsman } from '../js/Swordsman';
import { Zombie } from '../js/Zombie';
test('should check baseClass', () => {
    const hero1 = new Character('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(NaN);
    const hero2 = new Character('F');
    expect(new Character('F')).toThrow(new Error('В имени персонажа должно быть от 2 до 10 символов'));
    expect(hero2.name).toThrow();
    expect(hero2.name).toBeUndefined();
    const hero3 = new Character('Fil');
    hero3.health = 10;
    hero3.defence = 0;
    expect(hero3.damage(30)).toThrow();
    expect(hero3.damage(30)).toBe('Персонаж умер');
});
test('should check Bowerman', () => {
    const hero1 = new Bowerman('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(79);
    expect(hero1.attack).toBe(30);
    });
test('should check Daemon', () => {
    const hero1 = new Daemon('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(84.4);
    expect(hero1.attack).toBe(12);
    });
test('should check Magician', () => {
    const hero1 = new Magician('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(84.4);
    expect(hero1.attack).toBe(12);
    });
test('should check Undead', () => {
    const hero1 = new Undead('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(79);
    expect(hero1.attack).toBe(30);
    });
test('should check Swordsman', () => {
    const hero1 = new Swordsman('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(73.6);
    expect(hero1.attack).toBe(48);
    });
test('should check Zombie', () => {
    const hero1 = new Zombie('Philip');
    expect(hero1.name).toBe('Philip');
    expect(hero1.health).toBe(100);
    expect(hero1.level).toBe(1);
    hero1.levelUp();
    expect(hero1.level).toBe(2);
    hero1.damage(30);
    expect(hero1.health).toBe(73.6);
    expect(hero1.attack).toBe(48);
    });